# Generated by Django 5.2.4 on 2026-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsintLatestSnapshot',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=1024)),
                ('instagram', models.CharField(blank=True, default='', max_length=1024)),
                ('twitter', models.CharField(blank=True, default='', max_length=1024)),
                ('datasets', models.JSONField(default=dict)),
                ('collect_errors', models.JSONField(default=dict)),
                ('ai_bundle', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Latest OSINT snapshot',
            },
        ),
    ]
